Added access token, and check if exists

diff --git a/.github/workflows/generate-marketplace.yaml b/.github/workflows/generate-marketplace.yaml
--- a/.github/workflows/generate-marketplace.yaml
+++ b/.github/workflows/generate-marketplace.yaml
@@ -69,18 +69,25 @@ jobs:
       # Create branch
       - name: Create branch with new
         env:
-          GITHUB_TOKEN: ${{ secrets.MARKETPLACE_ACCESS_TOKEN }}
+          MARKETPLACE_ACCESS_TOKEN: ${{ secrets.MARKETPLACE_ACCESS_TOKEN }}
           USERNAME: Michaelliv
           REPO_PATH: funcitons-marketplace
         run: |
+          BRANCH_NAME=marketplace-doc-gen-$(git rev-parse --short "$GITHUB_SHA")
+
+          echo "Pushing to branch $BRANCH_NAME";
+
+          [ -z "${MARKETPLACE_ACCESS_TOKEN}" ] && {
+              echo 'Missing input "MARKETPLACE_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}".';
+              exit 1;
+          };
+
           cd marketplace
 
           git config --local user.name "github-worflow[bot]"
-
-          BRANCH_NAME=marketplace-doc-gen-$(git rev-parse --short "$GITHUB_SHA")
 
           git checkout -b $BRANCH_NAME
 
           git add -A && git commit -m "Your Message"
 
-          git push git push https://$USERNAME:$GITHUB_TOKEN@github.com/$REPO_PATH.git $BRANCH_NAME
+          git push git push https://$USERNAME:MARKETPLACE_ACCESS_TOKEN@github.com/$REPO_PATH.git $BRANCH_NAME
